-- AlterTable
ALTER TABLE "User" ADD COLUMN "banner" TEXT;
ALTER TABLE "User" ADD COLUMN "birthday" TEXT;
ALTER TABLE "User" ADD COLUMN "city" TEXT;
ALTER TABLE "User" ADD COLUMN "country" TEXT;
ALTER TABLE "User" ADD COLUMN "interests" TEXT;
ALTER TABLE "User" ADD COLUMN "pronouns" TEXT;
ALTER TABLE "User" ADD COLUMN "socialLinks" TEXT;
ALTER TABLE "User" ADD COLUMN "status" TEXT;
ALTER TABLE "User" ADD COLUMN "themeColor" TEXT;
ALTER TABLE "User" ADD COLUMN "website" TEXT;
